# Generated by Django 3.2.6 on 2021-08-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productSold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesdate', models.DateField()),
                ('pid', models.IntegerField(default=-1)),
                ('total_qty', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesdate', models.DateField()),
                ('cid', models.IntegerField(default=-1)),
                ('pid', models.IntegerField(default=-1)),
                ('qty', models.IntegerField(default=0)),
                ('sourcefile', models.CharField(max_length=100)),
                ('createddate', models.DateField()),
            ],
        ),
    ]
